name: MongoDB

on: [push]

jobs:  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [3.6, 4.0, 4.2]

    steps:
    - name: Start MongoDB v${{ matrix.mongodb-version }}
      uses: supercharge/mongodb-github-action@1.2.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: echo "done"
    - run: systemctl status mongod
